version: '3.5'

services:

  stream-transform:
    container_name: stream-transform
    image: frekele/gradle:latest
    networks:
      - streams-net
    volumes:
      - ./stream-transform-example:/root/stream-transform
  
  table-state:
    container_name: table-state
    image: frekele/gradle:latest
    hostname: table-state-app
    ports:
      - "8787:8787"
      - "5006:5006"
    networks:
      - streams-net
    volumes:
      - ./table-state-example:/root/table-state

  extract:
    container_name: extractor
    image: oracle/db-12.2-goldengate-standard:19.1.0.0.1-patched
    networks:
      - streams-net
    environment:
      ORACLE_PWD: "w"
      ORACLE_SID: "ORCLCDB"
    volumes:
      - ./goldengate-config/dirprm-standard:/u01/app/ogg/dirprm

  replicat:
    container_name: replicat
    image: oracle/goldengate-standard-bigdata:12.3.0.1.2-patched
    networks:
      - streams-net
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    volumes:
      - ./goldengate-config/dirprm-bigdata:/u01/app/ogg/dirprm

  zookeeper:
    hostname: zookeeper
    image: "confluentinc/cp-zookeeper:5.3.0"
    networks:
      - streams-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: "confluentinc/cp-enterprise-kafka:5.3.0"
    ports:
      - "9092:9092"
    hostname: kafka
    networks:
      - streams-net
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_METRIC_REPORTERS: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
      CONFLUENT_METRICS_REPORTER_TOPIC_CREATE: "false"
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "kafka:9092"
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100

  schema-registry:
    hostname: schema-registry
    image: "confluentinc/cp-schema-registry:5.3.0"
    ports:
      - "8081:8081"
    networks:
      - streams-net
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081

  ksql-server:
    hostname: ksql-server
    image: "confluentinc/cp-ksql-server:5.3.0"
    ports:
      - "8088:8088"
    networks:
      - streams-net
    environment:
      KSQL_CONFIG_DIR: "/etc/ksql"
      KSQL_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/ksql/log4j-rolling.properties"
      KSQL_BOOTSTRAP_SERVERS: "kafka:9092"
      KSQL_HOST_NAME: ksql-server
      KSQL_APPLICATION_ID: "streams-demo"
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_CACHE_MAX_BYTES_BUFFERING: 0
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KSQL_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
      KSQL_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
      KSQL_KSQL_SERVER_UI_ENABLED: "false"

  control-center:
    hostname: control-center
    image: confluentinc/cp-enterprise-control-center:5.3.0
    restart: always
    networks:
      - streams-net
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "kafka:9092"
      CONTROL_CENTER_ZOOKEEPER_CONNECT: "zookeeper:2181"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_REPLICATION: 1
      CONTROL_CENTER_INTERNAL_TOPICS_REPLICATION: 1
      CONTROL_CENTER_COMMAND_TOPIC_REPLICATION: 1
      CONTROL_CENTER_METRICS_TOPIC_REPLICATION: 1
      CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS: 1
      CONTROL_CENTER_STREAMS_CONSUMER_REQUEST_TIMEOUT_MS: "960032"
      CONTROL_CENTER_KSQL_URL: "http://ksql-server:8088"
      CONTROL_CENTER_KSQL_ADVERTISED_URL: "http://localhost:8088"
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"


networks:
  streams-net:
